#!/usr/bin/env php
<?php

$packageRoot = __DIR__ . '/..';

$version = $argv[1] ?? null;
is_numeric($version) ?: throw new \RuntimeException('Version must be defined as first argument', 1782626938);

if (file_exists($packageRoot . '/original')) {
    echo sprintf('Warning not version %s cloning into "original" because clone exist. Remove beforehand.', $version);
    echo PHP_EOL;
} else {
    mkdir($packageRoot . '/original');
    exec(sprintf('git -C %s clone git@github.com:neos/contentgraph-doctrinedbaladapter.git --depth 1 --branch %s contentgraph-doctrinedbaladapter', escapeshellarg($packageRoot . '/original'), escapeshellarg($version)));
    exec(sprintf('git -C %s clone git@github.com:neos/contentrepository-dbal.git --depth 1 --branch %s contentrepository-dbal', escapeshellarg($packageRoot . '/original'), escapeshellarg($version)));
}

if (file_exists($packageRoot . '/src/Generated')) {
    echo 'Error "src/Generated" is not empty. Remove beforehand.';
    echo PHP_EOL;
    exit(1);
}
mkdir($packageRoot . '/src/Generated', recursive: true);

$originalSources = new \RecursiveIteratorIterator(
    new \RecursiveDirectoryIterator($packageRoot . '/original/contentgraph-doctrinedbaladapter/src')
);

/** @var \SplFileInfo $originalSourceFile */
foreach ($originalSources as $originalSourceFile) {
    $relativePathName = str_replace($packageRoot . '/original/contentgraph-doctrinedbaladapter/src/', '', $originalSourceFile->getPathname());
    $newAbsolutePathName = $packageRoot . '/src/Generated/ContentGraph/' . $relativePathName;

    if ($originalSourceFile->isDir() && !file_exists($newAbsolutePathName)) {
        mkdir($newAbsolutePathName, recursive: true);
    }
    if ($originalSourceFile->isFile()) {
        $newContents = file_get_contents($originalSourceFile->getPathname());
        $newContents = str_replace(
            [
                <<<PHP
                Neos\ContentGraph\DoctrineDbalAdapter
                PHP,
                <<<PHP
                Neos\ContentRepository\Dbal
                PHP
            ],
            [
                <<<PHP
                Neos\ContentGraph\DoctrineDbalAdapter\Compatibility\Generated\ContentGraph
                PHP,
                <<<PHP
                Neos\ContentGraph\DoctrineDbalAdapter\Compatibility\Generated\Dbal
                PHP
            ],
            $newContents
        );

        if ($originalSourceFile->getFilename() === 'DoctrineDbalContentGraphProjectionFactory.php') {
            $newContents = str_replace(
                [
                    <<<PHP
                    final class DoctrineDbalContentGraphProjectionFactory implements ContentGraphProjectionFactoryInterface
                    {
                    PHP
                ],
                [
                    <<<PHP
                    final class DoctrineDbalContentGraphProjectionFactory
                    {
                    PHP
                ],
                $newContents
            );
        }

        file_put_contents($newAbsolutePathName, $newContents);
    }
}

$originalSources = new \RecursiveIteratorIterator(
        new \RecursiveDirectoryIterator($packageRoot . '/original/contentrepository-dbal/Classes')
);

/** @var \SplFileInfo $originalSourceFile */
foreach ($originalSources as $originalSourceFile) {
    $relativePathName = str_replace($packageRoot . '/original/contentrepository-dbal/Classes/', '', $originalSourceFile->getPathname());
    $newAbsolutePathName = $packageRoot . '/src/Generated/Dbal/' . $relativePathName;

    if ($originalSourceFile->isDir() && !file_exists($newAbsolutePathName)) {
        mkdir($newAbsolutePathName, recursive: true);
    }
    if ($originalSourceFile->isFile()) {
        $newContents = file_get_contents($originalSourceFile->getPathname());
        $newContents = str_replace(
                [
                    <<<PHP
                    Neos\ContentRepository\Dbal
                    PHP
                ],
                [
                    <<<PHP
                    Neos\ContentGraph\DoctrineDbalAdapter\Compatibility\Generated\Dbal
                    PHP
                ],
                $newContents
        );

        if ($originalSourceFile->getFilename() === 'DoctrineSubscriptionStore.php') {
            continue;
        }

        file_put_contents($newAbsolutePathName, $newContents);
    }
}
