
Neos:
  ContentRepositoryRegistry:
    presets:
      default:
        contentGraphProjection:
          subscription: contentGraph
          factoryObjectName: Neos\ContentGraph\DoctrineDbalAdapter\Compatibility\OldDoctrineDbalContentGraphProjectionFactory

        projections:
          'contentGraph_v1':
            factoryObjectName: Neos\ContentGraph\DoctrineDbalAdapter\Compatibility\NewDoctrineDbalContentGraphProjectionFactory
