
Neos:
  ContentRepositoryRegistry:
    presets:
      default:
        contentGraphProjection:
          factoryObjectName: Neos\ContentGraph\DoctrineDbalAdapter\Compatibility\OldDoctrineDbalContentGraphProjectionFactory
