Neos:
  Flow:
    object:
      includeClasses:
        # disable proxies for generated code
        "Neos.ContentGraph.DoctrineDbalAdapter.Compatibility":
          - "Neos\\\\ContentGraph\\\\DoctrineDbalAdapter\\\\Compatibility(?!\\\\Generated\\\\)"
